Add support to handle different exceptions
AY2324S1-CS2103T-W16-3/tp pull request #75
Opened 2023-10-15 16:41 UTC by RSXIX

Added error handling for non negative integer inputs for index, missing index, or index out of bounds for the given model

Ammended existing code such that above errors do not cause the program to throw an error but rather a new Command Result is returned. This ensures the code works seamlessly.

2023-10-16 04:41 UTC, brendanneojw commented
Please make sure that the CI checks passes before we perform any merging of pull requests (minimally). Codecov fails can be ignored for now

2023-10-16 04:42 UTC, brendanneojw commented
Please make sure to comment Closes #(issue number) in your comment so after the merge, it will automatically closes the issue.

2023-10-16 04:48 UTC, brendanneojw requested changes

2023-10-16 04:48 UTC, brendanneojw commented on src/main/java/seedu/address/logic/parser/exceptions/MissingIndexException.java
> +public class MissingIndexException extends ParseException {
Nice way to handle the different exceptions by inheriting from ParseException.

2023-10-16 04:48 UTC, brendanneojw commented on src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
> +            return new DeleteCommand(placeholderIndex, pe);
For the catch clause, I think it is not right to return from the function. We still have to throw an exception regardless. Here is a good read from [stackoverflow](https://stackoverflow.com/questions/36676929/can-i-return-false-from-a-try-and-catch-instead-of-throwing-exception)

2023-10-16 04:48 UTC, brendanneojw commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            return new CommandResult(Messages.MESSAGE_NOT_FOUND_INDEX);
For if clause, it is okay to return something since it does not guarantee that a exception will be thrown. So this is good!

2023-10-16 04:48 UTC, brendanneojw commented on src/main/java/seedu/address/logic/Messages.java
> +    public static final String MESSAGE_IMPOSSIBLE_INDEX = "Error: The parameter is not of the type positive integer";
Seems like this can be used for features that uses indexes as well. Thank you for the initiative.

2023-10-17 03:17 UTC, brendanneojw approved these changes
LGTM

2023-10-17 03:42 UTC, suryanshkushwaha commented
LGTM!

2023-10-17 03:42 UTC, merged

2023-10-17 08:09 UTC, brendanneojw commented
Closes #6

2023-10-19 15:49 UTC, brendanneojw commented
Closes #65 as well